### PR TITLE
Talk plugin

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

This is my 2020 Hackathon submission.  
It's a small plugin to integrate real-time voice communication in Mattermost.
More info can be found in the attached file.

### CODE REVIEW

**Comment by jespino** [comment]
I love this, really cool!!

**Comment by streamer45** [comment]
> I love this, really cool!!

Thank you :+1: Sorry for the slight conflict. It really wasn't planned. I wanted to do this since forever so I went for it even though I knew you guys were working on something similar.

**Comment by jespino** [comment]
Actually, I really like the fact that you did it too, because your interface is very interesting, and is very different from mine, so... we can explore that idea too. Besides, you based your's in pion, we used mumble, so is a very different approach there. Probably if we want to include this feature in the product as something that we going to maintain and give a lot of energy, pion would be my option. For something that we want to save costs of maintenance, I would prefer mumble, because is already mature and battle tested, but again, two different approaches that can give a lot to think about for this.

**Comment by streamer45** [comment]
> Actually, I really like the fact that you did it too, because your interface is very interesting, and is very different from mine, so... we can explore that idea too. Besides, you based your's in pion, we used mumble, so is a very different approach there. Probably if we want to include this feature in the product as something that we going to maintain and give a lot of energy, pion would be my option. For something that we want to save costs of maintenance, I would prefer mumble, because is already mature and battle tested, but again, two different approaches that can give a lot to think about for this.

Indeed, lot of food for thought. I am super excited to finally see such momentum in the a/v space :tada:

**Review by gabrieljackson — APPROVED** [review]

**Pull request merged**
